[workspace]
members = [
    "crates/typelude",
    "crates/typelude-bool",
    "crates/typelude-col",
    "crates/typelude-num",
    "crates/typelude-str",
    # "crates/typelude-core",
    "crates/typelude-std",
    "crates/typelude-vm",
    "crates/typelude-macros",
    "tooling/typelude-tooling-core",
    "tooling/typelude-tooling-cargo-profile",
    "tooling/typelude-tooling-semantic-api",
    "tooling/typelude-tooling-rustc",
    "tooling/typelude-tooling-typelude",
    "tooling/typelude-tooling-cli",
    "tooling/typelude-tooling-rustc-private", "crates/typelude-lambda", "crates/typelude-wasm",
]
resolver = "2"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
missing_errors_doc = "warn"
missing_panics_doc = "warn"
todo = "warn"
print_stdout = "warn"
# pedantic = "warn" # Uncomment iteratively to avoid overwhelming errors initially
