[workspace]
members = [
    "crates/typelude",
    # "crates/typelude-core",
    "crates/typelude-std",
    "crates/typelude-vm",
    "crates/typelude-macros",
    "crates/typelude-tooling-core",
    "crates/typelude-tooling-semantic-api",
    "crates/typelude-tooling-rustc",
    "crates/typelude-tooling-typelude",
    "crates/typelude-tooling-cli",
    "crates/typelude-tooling-rustc-private",
]
resolver = "2"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
missing_errors_doc = "warn"
missing_panics_doc = "warn"
todo = "warn"
print_stdout = "warn"
# pedantic = "warn" # Uncomment iteratively to avoid overwhelming errors initially
