unstable_features = true
style_edition = "2024"

max_width = 99
tab_spaces = 4
hard_tabs = false
newline_style = "Auto"

indent_style = "Block"

use_small_heuristics = "Off" # Disable small heuristics for consistent formatting
where_single_line = false # Where
overflow_delimited_expr = true # Generics

# imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Macro formatting
format_macro_bodies = true
format_macro_matchers = true

# Literals and matching
hex_literal_case = "Upper"
match_block_trailing_comma = true
# error_on_line_overflow = false # Optional: avoid failure on massive lines
format_code_in_doc_comments = true
wrap_comments = true
