[build]
incremental = false # fibonacciが50GBになります
rustflags = [
  "-Z",
  "verbose-internals",
  "-Z",
  "macro-backtrace",
  "-Z",
  "write-long-types-to-disk=yes",
  # "-Z",
  # "no-embed-metadata",
  # "--diagnostic-width=120", # Uncomment if you have a wide terminal
]

[alias]
type-check = "check --lib -v"
big-type-check = "rustc --lib -- -Z print-type-sizes"
expand-check = "expand --lib"
pedantic-check = "clippy -- -W clippy::pedantic"

[unstable]
build-analysis = true

[build.analysis]
enabled = true
