[package]
name = "typelude"
version = "0.1.0"
edition = "2024"
rust-version = "1.91.0"
description = "Type-level programming utilities for Rust"
license = "MIT"

[features]
default = ["nightly"]
nightly = [
    # "typelude-core/nightly",
    "typelude-std/nightly",
    "typelude-str/nightly",
    "typelude-vm/nightly",
    "typelude-wasm/nightly",
]

[dependencies]
# typelude-core = { path = "../typelude-core", default-features = false }
typelude-std = { path = "../typelude-std", default-features = false }
typelude-vm = { path = "../typelude-vm", default-features = false }
typelude-wasm = { path = "../typelude-wasm", default-features = false }
typelude-str = { path = "../typelude-str", default-features = false, features = ["nightly"] }
typelude-macros = { path = "../typelude-macros" }
typenum = { version = "1.19.0", features = ["const-generics"] }

[dev-dependencies]
static_assertions = "1.1.0"
trybuild = "1.0.114"

[lints.rust]
unsafe_code = "deny"
